apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 280466971911.dkr.ecr.ap-northeast-2.amazonaws.com/demo-frontend
  newName: 280466971911.dkr.ecr.ap-northeast-2.amazonaws.com/demo-frontend
  newTag: "92592020"
resources:
- ../../base
patchesStrategicMerge:
- front-deployment-patch.yaml
- front-service-patch.yaml
